version: '3'

services:

 ghost:
  image: ghost:latest
  restart: always
  ports:
   - 2369:2369
  volumes:
  - ./data-ghost-content/config.production.json:/var/lib/ghost/config.production.json:z #overwrite default settings 
  - ./data-ghost-content:/var/lib/ghost/content

volumes:
 data-ghost-content:

